name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event"
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."

  DeployDev:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    needs: [Build]
    environment:
      name: DEV
      url: 'http://dev.api.copeland.com'
    steps:
      - name: Deploy to DEV
        run: echo Deploying to DEV environment...
      - run: echo "This job's status is ${{ job.status }}."


  DeploySit:
    name: Deploy to SIT
    runs-on: ubuntu-latest
    needs: [DeployDev]
    environment:
      name: SIT
      url: 'http://sit.api.copeland.com'
    steps:
      - name: Deploy to SIT
        run: echo Deploying to SIT environment...
      - run: echo "This job's status is ${{ job.status }}."
